### ISSUE TITLE
Master fails to build here...

### ISSUE THREAD

**Issue by CaptainBloodz** [Miezhiko/Haku#2]
[dev-haskell:haku-9999-r1:20230730-013514.log.gz](https://github.com/Miezhiko/Haku/files/12208252/dev-haskell.haku-9999-r1.20230730-013514.log.gz)

9999-r1 is just to force ansi-terminal & base-unicode-symbols packages.

**Comment by Miezhiko** [comment]
mhm, strange error

```
      Expected: Command (HakuMonad m) m
                -> HakuMonad m -> HakuMonad m -> [String] -> m ()
        Actual: Command (HakuMonad m) m
                -> HakuMonad m => HakuMonad m -> [String] -> m ()
```

it even builds with ghc-8.10.3 on CI as you see: https://github.com/Miezhiko/Haku/actions/runs/5622984405/job/15236681753
and builds for me on ghc 9.4.x

possibly some of deps installing by portage is outdated or conflicting, you can try building in sandbox.

however this is code where it fails

```haskell
hakuHandle ∷ Command τ (ReaderT HakuEnv IO)
          -> [τ -> τ]
          -> [String]
          -> HakuEnv -> IO ()
hakuHandle cmd ss xs = runReaderT (handleM cmd ss xs)
  where handleM ∷ HakuMonad m ⇒ Command τ m -> [τ -> τ] -> [String] -> m ()
        handleM = liftM2 (∘) handler (foldl (flip id) ∘ state)
```

try to remove type specifier from it and build (e.g. like this)

```haskell
--hakuHandle ∷ Command τ (ReaderT HakuEnv IO)
--          -> [τ -> τ]
--          -> [String]
--          -> HakuEnv -> IO ()
hakuHandle cmd ss xs = runReaderT (handleM cmd ss xs)
  where handleM = liftM2 (∘) handler (foldl (flip id) ∘ state)
```

that even could work as temporary solution

**Comment by CaptainBloodz** [comment]
Thks 4 proposal.

Just tried to patch with

[patch.patch.gz](https://github.com/Miezhiko/Haku/files/12823742/patch.patch.gz)

Outputs:

[38 of 38] Compiling Main             ( src/Haku.hs, dist/build/haku/haku-tmp/Main.dyn_o )

src/Haku.hs:32:30: error:
    • Couldn't match kind ‘Constraint’ with ‘*’
      When matching types
        HakuMonad m1 :: Constraint
        (MonadReader HakuEnv m1, MonadIO m1) :: Constraint
      Expected: Command (HakuMonad m1) m1
                -> HakuMonad m1 -> HakuMonad m1 -> [String] -> m1 ()
        Actual: Command (HakuMonad m1) m1 -> HakuMonad m1 ~> m1
    • In the second argument of ‘liftM2’, namely ‘handler’
      In the expression: liftM2 (∘) handler (foldl (flip id) ∘ state)
      In an equation for ‘handleM’:
          handleM = liftM2 (∘) handler (foldl (flip id) ∘ state)
    • Relevant bindings include
        handleM :: Command τ1 m1 -> [τ1 -> τ1] -> [String] -> m1 ()
          (bound at src/Haku.hs:32:9)
   |
32 |         handleM = liftM2 (∘) handler (foldl (flip id) ∘ state)
   |                              ^^^^^^^
 * ERROR: dev-haskell/haku-9999-r1::local failed (compile phase):
 *   setup build failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_compile
 *   environment, line 2528:  Called haskell-cabal_src_compile
 *   environment, line 2185:  Called cabal_src_compile
 *   environment, line  994:  Called cabal-build
 *   environment, line  774:  Called die
 * The specific snippet of code:
 *       ./setup "$@" || die "setup build failed"

Maybe ebuild file has issue:

/var/db/repos/local/dev-haskell/haku/haku-9999-r1.ebuild



# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

CABAL_FEATURES="bin profile haddock hoogle hscolour"
inherit haskell-cabal git-r3

CABAL_PN="Haku"

MY_PN="Haku"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="scripty thing experiment"
HOMEPAGE="https://github.com/Miezhiko/${MY_PN}"
EGIT_REPO_URI="https://github.com/Miezhiko/${MY_PN}.git"

LICENSE="LGPLv2"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"

#dev-haskell/base-unicode-symbols:=[profile?]
RDEPEND="
        dev-haskell/base-unicode-symbols
        dev-haskell/ansi-terminal
        dev-haskell/parsec
        dev-haskell/split
        dev-haskell/yaml
        >=dev-lang/ghc-8.0:=
"
DEPEND="${RDEPEND}
        >=dev-haskell/cabal-2.0
"

S="${WORKDIR}/${P}"

src_configure() {
        cabal-mksetup
        haskell-cabal_src_configure
}


ghc here as:

Installed versions:  9.0.2-r4(0/9.0.2)^t(12:26:56 18/03/2023)(ghcbootstrap gmp profile -big-endian -binary -doc -elfutils -ghcmakebinary -llvm -numa -test -unregisterised)

**Comment by Miezhiko** [comment]
@CaptainBloodz very complicated error, but seems like it's because of GHC version, at least I was told so

and it seems like it was working on GHC 8.10, then broken on 9.0+, then wroking again on 9.4.5+ (or 9.6.2)
maybe I should recode this to be more universal if I will only understand how...

**Comment by Miezhiko** [comment]
okay, should be fixed with help of Melissa

**Comment by Melvar** [comment]
To explain this slightly more: The particular way the function `handleM` is written relies on a behavior called “deep subsumption”, which was removed in GHC 9.0, but later re-added in GHC 9.2 (as an extension) due to backlash against the sudden removal. This means that only version 9.0.x cannot compile this code. As noted, I supplied Miezhiko with an alternate way to write `handleM` without relying on deep subsumption, which is thus guaranteed to work in all relevant GHC versions on all settings.

**Comment by CaptainBloodz** [comment]
Thks 4 fast explanation.
Sorry no ghc skills here :(.

However gentoo haskell overlay seems good enough to overcome gentoo's delay to upgrade.

As this will finally happen one day, I'm taking that temporary path which seems future proof.

**Comment by Miezhiko** [comment]
> Thks 4 fast explanation. Sorry no ghc skills here :(.
> 
> However gentoo haskell overlay seems good enough to overcome gentoo's delay to upgrade.
> 
> As this will finally happen one day, I'm taking that temporary path which seems future proof.

note that gentoo haskell is tend to be unstable, and you'll may have things rebuilding often, fix for ghc 9.0 for this project is applied so it's okay to stay too. but for my packages I usually rely on gentoo-haskell (newer stuff)

**Comment by Miezhiko** [comment]
@CaptainBloodz in addition for those missing things in ebuild you've discovered - may you open pull request or issue in my overlay so I will not forget to fix those.
